version: "3.7"

# Backend API
services:
  smart-brain-backend:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-backend
    environment:
      POSTGRES_URI: postgres://tommy:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-backend

  # Postgres database
  postgres:
    environment:
      POSTGRES_USER: tommy
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
